#!/bin/bash
cd ~
dpkg -S nano | grep "\.nanorc$" | awk '{print ("include " $2)}' > ~/.nanorc
wget -O ~/.bashrc https://raw.githubusercontent.com/imbicile/shell_colors/master/.bashrc
wget -O ~/.dircolors https://raw.githubusercontent.com/imbicile/shell_colors/master/.dircolors
cp .bashrc .nanorc .dircolors /root/
cp .bashrc .nanorc .dircolors /etc/skel/
